"use strict";
exports.__esModule = true;
var robotDeCasa_1 = require("./robotDeCasa");
var robotDePileta_1 = require("./robotDePileta");
var robotHogar = new robotDeCasa_1.RobotDeCasa('Sony', 220, 2020, true);
console.log(robotHogar.getMarca());
console.log(robotHogar.getModelo());
console.log(robotHogar.getPotencia());
console.log("aumentando potencia...");
robotHogar.aumentarPotencia();
console.log('nueva potencia ' + robotHogar.getPotencia());
robotHogar.limpiar(true);
var robotPileta = new robotDePileta_1.RobotDePileta('Piletero', 110, 2018, false);
console.log(robotPileta.getMarca());
console.log(robotPileta.getModelo());
console.log(robotPileta.getPotencia());
console.log("aumentando potencia...");
robotPileta.aumentarPotencia();
console.log('nueva potencia ' + robotPileta.getPotencia());
robotPileta.limpiar(true);
