"use strict";
exports.__esModule = true;
var auto_1 = require("./auto");
var autoDeportivo_1 = require("./autoDeportivo");
var autoComun = new auto_1.Auto('Ford', 2018, 'ABC 234');
autoComun.acelerar();
console.log('velocidad actual del auto ' + autoComun.getSpeed());
autoComun.acelerar();
console.log("marca del auto comun " + autoComun.getBrand());
console.log("modelo del auto comun " + autoComun.getModel());
console.log("patente del auto comun " + autoComun.getRegistry());
autoComun.mejorarModelo();
console.log("modelo mejorado del auto comun = " + autoComun.getModel());
console.log('velocidad actual del auto comun ' + autoComun.getSpeed());
var autoDeCarrera = new autoDeportivo_1.AutoDeportivo('Chevroley', 2020, 'DEF 789');
autoDeCarrera.acelerar();
console.log('velocidad actual del auto de carrera' + autoDeCarrera.getSpeed());
autoDeCarrera.acelerar();
console.log("marca del auto de carrera " + autoDeCarrera.getBrand());
console.log("modelo del auto de carrera " + autoDeCarrera.getModel());
console.log("patente del auto de carrera " + autoDeCarrera.getRegistry());
autoDeCarrera.mejorarModelo();
console.log("modelo mejorado del auto comun = " + autoDeCarrera.getModel());
console.log("velocidad actual del auto de carrera " + autoDeCarrera.getSpeed());
